Traceback (most recent call last):
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ax2 = plot_3d_view(ele_angle=-140,hori_angle=60)
p = ax2.scatter3D(ds_part[xname],
              ds_part[yname],
              ds_part[zname],
              c=ds_part[varname],      # color value of individual points is taken from their heights
              cmap="viridis"                           # the color mapping to be used. Other example options: winter, autumn, ...
              );
# ax2.invert_zaxis()
ax2.invert_xaxis()
cbar = plt.colorbar(p)
cbar.set_label(varname)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/xarray/core/dataset.py:1347[0m, in [0;36mDataset._construct_dataarray[0;34m(self, name)[0m
[1;32m   1346[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1347[0m     variable [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_variables[49m[43m[[49m[43mname[49m[43m][49m
[1;32m   1348[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:

[0;31mKeyError[0m: 'temperature (Celsius)'

During handling of the above exception, another exception occurred:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[15], line 5[0m
[1;32m      1[0m ax2 [38;5;241m=[39m plot_3d_view(ele_angle[38;5;241m=[39m[38;5;241m-[39m[38;5;241m140[39m,hori_angle[38;5;241m=[39m[38;5;241m60[39m)
[1;32m      2[0m p [38;5;241m=[39m ax2[38;5;241m.[39mscatter3D(ds_part[xname],
[1;32m      3[0m               ds_part[yname],
[1;32m      4[0m               ds_part[zname],
[0;32m----> 5[0m               c[38;5;241m=[39m[43mds_part[49m[43m[[49m[43mvarname[49m[43m][49m,      [38;5;66;03m# color value of individual points is taken from their heights[39;00m
[1;32m      6[0m               cmap[38;5;241m=[39m[38;5;124m"[39m[38;5;124mviridis[39m[38;5;124m"[39m                           [38;5;66;03m# the color mapping to be used. Other example options: winter, autumn, ...[39;00m
[1;32m      7[0m               );
[1;32m      8[0m [38;5;66;03m# ax2.invert_zaxis()[39;00m
[1;32m      9[0m ax2[38;5;241m.[39minvert_xaxis()

File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/xarray/core/dataset.py:1438[0m, in [0;36mDataset.__getitem__[0;34m(self, key)[0m
[1;32m   1436[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39misel([38;5;241m*[39m[38;5;241m*[39mkey)
[1;32m   1437[0m [38;5;28;01mif[39;00m utils[38;5;241m.[39mhashable(key):
[0;32m-> 1438[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_construct_dataarray[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m   1439[0m [38;5;28;01mif[39;00m utils[38;5;241m.[39miterable_of_hashable(key):
[1;32m   1440[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_copy_listed(key)

File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/xarray/core/dataset.py:1349[0m, in [0;36mDataset._construct_dataarray[0;34m(self, name)[0m
[1;32m   1347[0m     variable [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_variables[name]
[1;32m   1348[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:
[0;32m-> 1349[0m     _, name, variable [38;5;241m=[39m [43m_get_virtual_variable[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_variables[49m[43m,[49m[43m [49m[43mname[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdims[49m[43m)[49m
[1;32m   1351[0m needed_dims [38;5;241m=[39m [38;5;28mset[39m(variable[38;5;241m.[39mdims)
[1;32m   1353[0m coords: [38;5;28mdict[39m[Hashable, Variable] [38;5;241m=[39m {}

File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/xarray/core/dataset.py:185[0m, in [0;36m_get_virtual_variable[0;34m(variables, key, dim_sizes)[0m
[1;32m    183[0m split_key [38;5;241m=[39m key[38;5;241m.[39msplit([38;5;124m"[39m[38;5;124m.[39m[38;5;124m"[39m, [38;5;241m1[39m)
[1;32m    184[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(split_key) [38;5;241m!=[39m [38;5;241m2[39m:
[0;32m--> 185[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key)
[1;32m    187[0m ref_name, var_name [38;5;241m=[39m split_key
[1;32m    188[0m ref_var [38;5;241m=[39m variables[ref_name]

[0;31mKeyError[0m: 'temperature (Celsius)'
KeyError: 'temperature (Celsius)'

